# Generated by Django 4.2.7 on 2023-11-21 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0003_rename_q_type_question_input_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionresponse",
            old_name="answer",
            new_name="answers",
        ),
    ]
