# Generated by Django 4.2.7 on 2023-11-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0006_alter_question_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(max_length=150, verbose_name="Ответ"),
        ),
    ]
