version: '3.3'

services:
  db:
    container_name: quiz_db
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: quiz_back
    build:
      context: ./
    # command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn config.wsgi:application --bind 0:8000
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
      - static_data:/app/static/
      - media_data:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  static_data:
  media_data:
  db_data:
