# Generated by Django 4.2.7 on 2023-11-20 11:51

from django.conf import settings
from django.db import migrations


def create_first_superuser(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    CustomUser.objects.create(
        email=settings.ADMIN_EMAIL,
        password=settings.ADMIN_PASSWORD,
        is_staff=True,
        is_superuser=True,
        is_active=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_first_superuser)]
